name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    env:
      ENV_NAME: tests
      PYTHON: ${{ matrix.python-version }}
      OS: ${{ matrix.os }}
    name: Testing
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Get C Libraries Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install libfftw3-dev
          sudo apt-get install libgsl0-dev
      - name: Get C Libraries MacOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install fftw
          brew install gsl
          brew install libomp

      - name: Install the project
        run: uv sync --all-extras --all-groups --dev

      - name: Run Tests
        run: |
          uv run coverage run --parallel-mode -m pytest

      - name: Upload coverage report
        if: matrix.os == 'ubuntu-latest' && success()
        uses: codecov/codecov-action@v5.4.0
        with:
          files: "./coverage.xml"
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
